UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 67: ordinal not in range(128) approached. I need to make CERTAIN it displays the data error when it happens!